source = ~/.config/hypr/colors.conf

general {
    disable_loading_bar = true
    hide_cursor = false
    grace = 0
}

background {
    monitor =
    path = ~/.config/hypr/wallpapers/default.png
    blur_passes = 3
    blur_size = 8
    noise = 0.02
    brightness = 0.6
}

input-field {
    monitor =
    size = 260, 52
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    outer_color = $surface1
    inner_color = $mantle
    font_color = $text
    fade_on_empty = false
    placeholder_text = <span foreground="##a3a3b0">password...</span>
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = $text
    font_size = 78
    font_family = JetBrainsMono Nerd Font
    position = 0, 140
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %d %B")"
    color = $subtext
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 60
    halign = center
    valign = center
}
