# ────────────────────────────────
#  Per-app window rules
# ────────────────────────────────
windowrule = float, ^(pavucontrol)$
windowrule = float, ^(nm-connection-editor)$
windowrule = float, ^(blueman-manager)$
windowrule = float, title:^(Picture-in-Picture)$
windowrule = pin, title:^(Picture-in-Picture)$
windowrule = opacity 1.0 override, class:^(mpv)$
windowrule = idleinhibit fullscreen, class:^(mpv)$

layerrule = blur, waybar
layerrule = blur, rofi
layerrule = ignorezero, rofi
layerrule = blur, notifications
layerrule = ignorezero, notifications
